Написал модуль записи данных в файл
htmlacademy-nodejs/293513-kekstagram pull request #8
Opened 2018-10-07 19:41 UTC by SerjSidelnikov

2018-10-08 17:03 UTC, Donnyyyyy approved these changes

2018-10-08 17:07 UTC, Donnyyyyy requested changes
А где же тесты ? :0

2018-10-09 09:44 UTC, Donnyyyyy reviewed
UPD: сори, не заметил, что тесты - доп задание. Если не будешь их писать, то в интерфейсе академии отправь на проверку задание - приму!

2018-10-09 10:23 UTC, SerjSidelnikov commented
Я не знаю как правильно проверить запись и перезапись файла)

2018-10-09 10:23 UTC, merged