Написал сервер
htmlacademy-nodejs/293513-kekstagram pull request #9
Opened 2018-10-11 14:44 UTC by SerjSidelnikov

2018-10-12 22:16 UTC, Donnyyyyy requested changes
1. Сервер не умеет возвращать файлы из подпапок, так как имя файла всегда формируется как `path.basename(pathname);`
2. Лучше использовать не `res.end`, а `res.send` - первый вариант обычно используется чтобы быстро завершить запрос, обычно без данных с каким-то "коротким" результатом.

Если будут вопросы - можешь писать в телеграмм, чтобы получилось быстрее)

2018-10-13 12:41 UTC, SerjSidelnikov commented
res.send, вроде, только в express?

2018-10-13 20:07 UTC, Donnyyyyy requested changes
1. Убери листинг директорий
2. По `/` должен возвращаться `index.html`

к сожалению всё еще не смог получить файлы через сервер :( Начнем с пунктов 1 и 2

2018-10-14 15:38 UTC, Donnyyyyy approved these changes

2018-10-14 15:38 UTC, merged